### ISSUE TITLE
Error in console, doesn't work

### ISSUE THREAD

**Issue by ChicknTurtle** [sebseb7/GlobalVillagerCuring#1]
Using paper 1.20.6
```
[19:42:50 ERROR]: Could not pass event PlayerInteractAtEntityEvent to GlobalVillagerCuring v1.2
java.lang.ExceptionInInitializerError: null
	at GlobalVillagerCuring-1.2.jar/me.gwodny.events.GossipHandler.onPlayerInteractAtEntity(GossipHandler.java:25) ~[GlobalVillagerCuring-1.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-130-5d8e53d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2773) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onInteraction(ServerGamePacketListenerImpl.java:2826) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.dispatch(ServerboundInteractPacket.java:168) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2762) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-130-5d8e53d]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at GlobalVillagerCuring-1.2.jar/io.github.bananapuncher714.nbteditor.NBTEditor.<clinit>(NBTEditor.java:60) ~[GlobalVillagerCuring-1.2.jar:?]
	... 29 more
```

Server Plugins (19):
BetterBeaconRange, BlueMap, ClickVillagers, DiscordSRV, GlobalVillagerCuring, InstantRestock, LuckPerms, NBTAPI, PlaceholderAPI, ShulkerPacks, SkBee, Skript, *skript-placeholders, skript-reflect, spark, TAB, ViaBackwards, ViaVersion, VillagerStackableCuring

**Comment by EmanYm** [comment]
This is also happening on Minecraft 1.21.1
To be fair, it does claim to only work on versions up to 1.20.4
